export const translations = {
  en: {
    appName: "Al-Mumin",
    prayerTimes: "Prayer Times",
    quran: "Quran",
    hadith: "Hadith",
    tasbih: "Tasbih",
    qibla: "Qibla",
    settings: "Settings",
    nextPrayer: "Next Prayer",
    fajr: "Fajr",
    sunrise: "Sunrise",
    dhuhr: "Dhuhr",
    asr: "Asr",
    maghrib: "Maghrib",
    isha: "Isha",
    surah: "Surah",
    searchSurah: "Search Surah...",
    tasbihCount: "Tasbih Count",
    reset: "Reset",
    save: "Save",
    language: "Language",
    bangla: "Bangla",
    english: "English",
    locationAccess: "Please allow location access for accurate prayer times.",
    loading: "Loading...",
    audio: "Audio",
    translation: "Translation",
    arabic: "Arabic"
  },
  bn: {
    appName: "আল-মুমিন",
    prayerTimes: "নামাজের সময়",
    quran: "কুরআন",
    hadith: "হাদিস",
    tasbih: "তাসবিহ",
    qibla: "কিবলা",
    settings: "সেটিংস",
    nextPrayer: "পরবর্তী নামাজ",
    fajr: "ফজর",
    sunrise: "সূর্যোদয়",
    dhuhr: "যোহর",
    asr: "আসর",
    maghrib: "মাগরিব",
    isha: "এশা",
    surah: "সূরা",
    searchSurah: "সূরা খুঁজুন...",
    tasbihCount: "তাসবিহ গণনা",
    reset: "রিসেট",
    save: "সংরক্ষণ",
    language: "ভাষা",
    bangla: "বাংলা",
    english: "ইংরেজি",
    locationAccess: "সঠিক নামাজের সময়ের জন্য লোকেশন পারমিশন দিন।",
    loading: "লোড হচ্ছে...",
    audio: "অডিও",
    translation: "অনুবাদ",
    arabic: "আরবি",
    pronunciation: "উচ্চারণ",
    meaning: "অর্থ",
    dailyReminder: "দৈনিক রিমাইন্ডার",
    dua: "দুয়া ও জিকির",
    allDuas: "সকল দুয়া",
    searchDua: "দুয়া খুঁজুন...",
    hadithSource: "সূত্র",
    tasbihTarget: "লক্ষ্য",
    vibration: "ভাইব্রেশন",
    notifications: "নোটিফিকেশন",
    aboutApp: "অ্যাপ সম্পর্কে",
    privacyPolicy: "প্রাইভেসি পলিসি",
    readMore: "আরও পড়ুন",
    back: "ফিরে যান"
  }
};
